In [1]:
import pandas as pd
import numpy as np

In [4]:
sales_data = pd.read_csv(r"C:\Users\wwwsi\OneDrive\Documents\Project Brothers BBQ\Dataset _\raw\Total_Monthly_Sales.csv")

In [7]:
sales_data.head(10)

,date,month,total_stock_kg,leg_stock_kg,wings_stock_kg,lollipop_stock_kg,planned_customers,actual_customers_served,total_sales_amount,coupon_uses_count,leg_pieces_sold,wings_pieces_sold,lollipop_pieces_sold,leg_pieces_leftover,wings_pieces_leftover,lollipop_pieces_leftover,leg_leftover_kg,wings_leftover_kg,lollipop_leftover_kg
0,2026-02-01,February,15.0,6.0,4.0,5.0,53,53,7605,4,42,100,72,18,0,28,1.8,0.0,1.4
1,2026-02-02,February,15.0,6.0,4.0,5.0,58,58,8671,3,56,100,76,4,0,24,0.4,0.0,1.2
2,2026-02-03,February,15.0,6.0,4.0,5.0,60,60,8970,9,60,95,84,0,5,16,0.0,0.2,0.8
3,2026-02-04,February,15.0,6.0,4.0,5.0,60,60,8905,5,48,100,100,12,0,0,1.2,0.0,0.0
4,2026-02-05,February,15.0,6.0,4.0,5.0,54,54,7527,10,44,100,68,16,0,32,1.6,0.0,1.6
5,2026-02-06,February,15.0,6.0,4.0,5.0,47,47,6721,3,24,100,80,36,0,20,3.6,0.0,1.0
6,2026-02-07,February,15.0,6.0,4.0,5.0,51,51,6916,7,24,85,100,36,15,0,3.6,0.6,0.0
7,2026-02-08,February,15.0,6.0,4.0,5.0,51,51,7150,10,28,85,100,32,15,0,3.2,0.6,0.0
8,2026-02-09,February,15.0,6.0,4.0,5.0,44,44,7007,9,32,100,76,28,0,24,2.8,0.0,1.2
9,2026-02-10,February,15.0,6.0,4.0,5.0,45,45,7007,8,46,85,60,14,15,40,1.4,0.6,2.0

In [5]:
sales_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      120 non-null    str
 1   month                     120 non-null    str
 2   total_stock_kg            120 non-null    float64
 3   leg_stock_kg              120 non-null    float64
 4   wings_stock_kg            120 non-null    float64
 5   lollipop_stock_kg         120 non-null    float64
 6   planned_customers         120 non-null    int64
 7   actual_customers_served   120 non-null    int64
 8   total_sales_amount        120 non-null    int64
 9   coupon_uses_count         120 non-null    int64
 10  leg_pieces_sold           120 non-null    int64
 11  wings_pieces_sold         120 non-null    int64
 12  lollipop_pieces_sold      120 non-null    int64
 13  leg_pieces_leftover       120 non-null    int64
 14  wings_pieces_leftover     120 non-null    int64
 15  lollipop_pieces_leftover  120 non-null    int64
 16  leg_leftover_kg           120 non-null    float64
 17  wings_leftover_kg         120 non-null    float64
 18  lollipop_leftover_kg      120 non-null    float64
dtypes: float64(7), int64(10), str(2)
memory usage: 17.9 KB

In [6]:
sales_data.describe()

,total_stock_kg,leg_stock_kg,wings_stock_kg,lollipop_stock_kg,planned_customers,actual_customers_served,total_sales_amount,coupon_uses_count,leg_pieces_sold,wings_pieces_sold,lollipop_pieces_sold,leg_pieces_leftover,wings_pieces_leftover,lollipop_pieces_leftover,leg_leftover_kg,wings_leftover_kg,lollipop_leftover_kg
count,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,13.075000,5.230000,3.487250,4.357750,44.408333,44.408333,6505.525000,6.075000,35.716667,76.500000,70.266667,16.258333,10.383333,16.616667,1.625833,0.415333,0.830833
std,1.665329,0.666131,0.444044,0.555164,7.880937,7.880937,1196.529077,2.631939,10.284347,15.912048,16.648483,9.679308,11.428391,14.211596,0.967931,0.457136,0.710580
min,10.000000,4.000000,2.670000,3.330000,28.000000,28.000000,4121.000000,0.000000,14.000000,40.000000,32.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,11.575000,4.630000,3.085000,3.860000,39.000000,39.000000,5677.750000,4.000000,28.000000,65.000000,60.000000,9.000000,1.000000,3.000000,0.900000,0.040000,0.150000
50%,13.350000,5.340000,3.560000,4.450000,44.000000,44.000000,6324.500000,6.000000,35.000000,77.500000,68.000000,16.000000,5.000000,14.000000,1.600000,0.200000,0.700000
75%,14.900000,5.960000,3.970000,4.970000,51.000000,51.000000,7367.750000,8.000000,44.000000,90.000000,84.000000,23.250000,16.000000,26.000000,2.325000,0.640000,1.300000
max,15.000000,6.000000,4.000000,5.000000,60.000000,60.000000,9269.000000,16.000000,60.000000,100.000000,100.000000,38.000000,49.000000,48.000000,3.800000,1.960000,2.400000

In [12]:
sales_data["date"] = pd.to_datetime(sales_data["date"],errors = 'coerce')
sales_data["total_sales_amount"]=sales_data["total_sales_amount"].astype("float64")
sales_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      120 non-null    datetime64[us]
 1   month                     120 non-null    str
 2   total_stock_kg            120 non-null    float64
 3   leg_stock_kg              120 non-null    float64
 4   wings_stock_kg            120 non-null    float64
 5   lollipop_stock_kg         120 non-null    float64
 6   planned_customers         120 non-null    int64
 7   actual_customers_served   120 non-null    int64
 8   total_sales_amount        120 non-null    float64
 9   coupon_uses_count         120 non-null    int64
 10  leg_pieces_sold           120 non-null    int64
 11  wings_pieces_sold         120 non-null    int64
 12  lollipop_pieces_sold      120 non-null    int64
 13  leg_pieces_leftover       120 non-null    int64
 14  wings_pieces_leftover     120 non-null    int64
 15  lollipop_pieces_leftover  120 non-null    int64
 16  leg_leftover_kg           120 non-null    float64
 17  wings_leftover_kg         120 non-null    float64
 18  lollipop_leftover_kg      120 non-null    float64
dtypes: datetime64[us](1), float64(8), int64(9), str(1)
memory usage: 17.9 KB

In [13]:
sales_data.isnull().sum()

date                        0
month                       0
total_stock_kg              0
leg_stock_kg                0
wings_stock_kg              0
lollipop_stock_kg           0
planned_customers           0
actual_customers_served     0
total_sales_amount          0
coupon_uses_count           0
leg_pieces_sold             0
wings_pieces_sold           0
lollipop_pieces_sold        0
leg_pieces_leftover         0
wings_pieces_leftover       0
lollipop_pieces_leftover    0
leg_leftover_kg             0
wings_leftover_kg           0
lollipop_leftover_kg        0
dtype: int64

In [16]:
sales_data.duplicated().sum()
#sales_data[sales_data.duplicated(keep="last")]

Empty DataFrame
Columns: [date, month, total_stock_kg, leg_stock_kg, wings_stock_kg, lollipop_stock_kg, planned_customers, actual_customers_served, total_sales_amount, coupon_uses_count, leg_pieces_sold, wings_pieces_sold, lollipop_pieces_sold, leg_pieces_leftover, wings_pieces_leftover, lollipop_pieces_leftover, leg_leftover_kg, wings_leftover_kg, lollipop_leftover_kg]
Index: []

In [29]:
#Spotting outliers
Numerical_column = sales_data.select_dtypes(include=['number']).columns
for x in Numerical_column:
    Q1 = sales_data[x].quantile(0.25)
    Q3 = sales_data[x].quantile(0.75)
    IQR = Q3 - Q1

    #Determing outlier
    lower_bound = Q1-1.5*IQR
    upper_bound = Q3+1.5*IQR

    outlier = sales_data[(sales_data[x] < lower_bound) | (sales_data[x] > upper_bound)]
    print(f'\n{ x } :{outlier[x].count()}')

total_stock_kg :0

leg_stock_kg :0

wings_stock_kg :0

lollipop_stock_kg :0

planned_customers :0

actual_customers_served :0

total_sales_amount :0

coupon_uses_count :1

leg_pieces_sold :0

wings_pieces_sold :0

lollipop_pieces_sold :0

leg_pieces_leftover :0

wings_pieces_leftover :5

lollipop_pieces_leftover :0

leg_leftover_kg :0

wings_leftover_kg :5

lollipop_leftover_kg :0