In [1]:
import pandas as pd
import numpy as np

In [2]:
sales_data = pd.read_csv(r"C:\Users\wwwsi\OneDrive\Documents\Project Brothers BBQ\Dataset _\raw\Total_Monthly_Sales.csv")

In [3]:
sales_data.head(10)

,date,month,total_stock_kg,leg_stock_kg,wings_stock_kg,lollipop_stock_kg,planned_customers,actual_customers_served,total_sales_amount,coupon_uses_count,leg_pieces_sold,wings_pieces_sold,lollipop_pieces_sold,leg_pieces_leftover,wings_pieces_leftover,lollipop_pieces_leftover,leg_leftover_kg,wings_leftover_kg,lollipop_leftover_kg
0,2026-02-01,February,15.0,6.0,4.0,5.0,53,53,7605,4,42,100,72,18,0,28,1.8,0.0,1.4
1,2026-02-02,February,15.0,6.0,4.0,5.0,58,58,8671,3,56,100,76,4,0,24,0.4,0.0,1.2
2,2026-02-03,February,15.0,6.0,4.0,5.0,60,60,8970,9,60,95,84,0,5,16,0.0,0.2,0.8
3,2026-02-04,February,15.0,6.0,4.0,5.0,60,60,8905,5,48,100,100,12,0,0,1.2,0.0,0.0
4,2026-02-05,February,15.0,6.0,4.0,5.0,54,54,7527,10,44,100,68,16,0,32,1.6,0.0,1.6
5,2026-02-06,February,15.0,6.0,4.0,5.0,47,47,6721,3,24,100,80,36,0,20,3.6,0.0,1.0
6,2026-02-07,February,15.0,6.0,4.0,5.0,51,51,6916,7,24,85,100,36,15,0,3.6,0.6,0.0
7,2026-02-08,February,15.0,6.0,4.0,5.0,51,51,7150,10,28,85,100,32,15,0,3.2,0.6,0.0
8,2026-02-09,February,15.0,6.0,4.0,5.0,44,44,7007,9,32,100,76,28,0,24,2.8,0.0,1.2
9,2026-02-10,February,15.0,6.0,4.0,5.0,45,45,7007,8,46,85,60,14,15,40,1.4,0.6,2.0

In [4]:
sales_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      120 non-null    str
 1   month                     120 non-null    str
 2   total_stock_kg            120 non-null    float64
 3   leg_stock_kg              120 non-null    float64
 4   wings_stock_kg            120 non-null    float64
 5   lollipop_stock_kg         120 non-null    float64
 6   planned_customers         120 non-null    int64
 7   actual_customers_served   120 non-null    int64
 8   total_sales_amount        120 non-null    int64
 9   coupon_uses_count         120 non-null    int64
 10  leg_pieces_sold           120 non-null    int64
 11  wings_pieces_sold         120 non-null    int64
 12  lollipop_pieces_sold      120 non-null    int64
 13  leg_pieces_leftover       120 non-null    int64
 14  wings_pieces_leftover     120 non-null    int64
 15  lollipop_pieces_leftover  120 non-null    int64
 16  leg_leftover_kg           120 non-null    float64
 17  wings_leftover_kg         120 non-null    float64
 18  lollipop_leftover_kg      120 non-null    float64
dtypes: float64(7), int64(10), str(2)
memory usage: 17.9 KB

In [5]:
sales_data.describe()

,total_stock_kg,leg_stock_kg,wings_stock_kg,lollipop_stock_kg,planned_customers,actual_customers_served,total_sales_amount,coupon_uses_count,leg_pieces_sold,wings_pieces_sold,lollipop_pieces_sold,leg_pieces_leftover,wings_pieces_leftover,lollipop_pieces_leftover,leg_leftover_kg,wings_leftover_kg,lollipop_leftover_kg
count,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000,120.000000
mean,13.075000,5.230000,3.487250,4.357750,44.408333,44.408333,6505.525000,6.075000,35.716667,76.500000,70.266667,16.258333,10.383333,16.616667,1.625833,0.415333,0.830833
std,1.665329,0.666131,0.444044,0.555164,7.880937,7.880937,1196.529077,2.631939,10.284347,15.912048,16.648483,9.679308,11.428391,14.211596,0.967931,0.457136,0.710580
min,10.000000,4.000000,2.670000,3.330000,28.000000,28.000000,4121.000000,0.000000,14.000000,40.000000,32.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,11.575000,4.630000,3.085000,3.860000,39.000000,39.000000,5677.750000,4.000000,28.000000,65.000000,60.000000,9.000000,1.000000,3.000000,0.900000,0.040000,0.150000
50%,13.350000,5.340000,3.560000,4.450000,44.000000,44.000000,6324.500000,6.000000,35.000000,77.500000,68.000000,16.000000,5.000000,14.000000,1.600000,0.200000,0.700000
75%,14.900000,5.960000,3.970000,4.970000,51.000000,51.000000,7367.750000,8.000000,44.000000,90.000000,84.000000,23.250000,16.000000,26.000000,2.325000,0.640000,1.300000
max,15.000000,6.000000,4.000000,5.000000,60.000000,60.000000,9269.000000,16.000000,60.000000,100.000000,100.000000,38.000000,49.000000,48.000000,3.800000,1.960000,2.400000

In [6]:
sales_data["date"] = pd.to_datetime(sales_data["date"],errors = 'coerce')
sales_data["total_sales_amount"]=sales_data["total_sales_amount"].astype("float64")
sales_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      120 non-null    datetime64[us]
 1   month                     120 non-null    str
 2   total_stock_kg            120 non-null    float64
 3   leg_stock_kg              120 non-null    float64
 4   wings_stock_kg            120 non-null    float64
 5   lollipop_stock_kg         120 non-null    float64
 6   planned_customers         120 non-null    int64
 7   actual_customers_served   120 non-null    int64
 8   total_sales_amount        120 non-null    float64
 9   coupon_uses_count         120 non-null    int64
 10  leg_pieces_sold           120 non-null    int64
 11  wings_pieces_sold         120 non-null    int64
 12  lollipop_pieces_sold      120 non-null    int64
 13  leg_pieces_leftover       120 non-null    int64
 14  wings_pieces_leftover     120 non-null    int64
 15  lollipop_pieces_leftover  120 non-null    int64
 16  leg_leftover_kg           120 non-null    float64
 17  wings_leftover_kg         120 non-null    float64
 18  lollipop_leftover_kg      120 non-null    float64
dtypes: datetime64[us](1), float64(8), int64(9), str(1)
memory usage: 17.9 KB

In [7]:
sales_data.isnull().sum()

date                        0
month                       0
total_stock_kg              0
leg_stock_kg                0
wings_stock_kg              0
lollipop_stock_kg           0
planned_customers           0
actual_customers_served     0
total_sales_amount          0
coupon_uses_count           0
leg_pieces_sold             0
wings_pieces_sold           0
lollipop_pieces_sold        0
leg_pieces_leftover         0
wings_pieces_leftover       0
lollipop_pieces_leftover    0
leg_leftover_kg             0
wings_leftover_kg           0
lollipop_leftover_kg        0
dtype: int64

In [8]:
sales_data.duplicated().sum()
#sales_data[sales_data.duplicated(keep="last")]

np.int64(0)

In [9]:
#Spotting outliers
Numerical_column = sales_data.select_dtypes(include=['number']).columns
for x in Numerical_column:
    Q1 = sales_data[x].quantile(0.25)
    Q3 = sales_data[x].quantile(0.75)
    IQR = Q3 - Q1

    #Determing outlier
    lower_bound = Q1-1.5*IQR
    upper_bound = Q3+1.5*IQR

    outlier = sales_data[(sales_data[x] < lower_bound) | (sales_data[x] > upper_bound)]
    print(f'\n{ x } :{outlier[x].count()}')

total_stock_kg :0

leg_stock_kg :0

wings_stock_kg :0

lollipop_stock_kg :0

planned_customers :0

actual_customers_served :0

total_sales_amount :0

coupon_uses_count :1

leg_pieces_sold :0

wings_pieces_sold :0

lollipop_pieces_sold :0

leg_pieces_leftover :0

wings_pieces_leftover :5

lollipop_pieces_leftover :0

leg_leftover_kg :0

wings_leftover_kg :5

lollipop_leftover_kg :0

In [10]:
# Validating Data quality
# 1. Validating total stocks with splited stocks [ leg + wings + lolipop = total_stocks]
pd.DataFrame(np.isclose(sales_data['total_stock_kg'],
                        sales_data[['leg_stock_kg','wings_stock_kg','lollipop_stock_kg']].sum(axis=1),
                        atol =1e-8)).value_counts()

0
True    120
Name: count, dtype: int64

In [11]:
# 2. Validating Planned_Customer <= Served_Customer
(sales_data['planned_customers'] <= sales_data['actual_customers_served'] ).all()

np.True_

In [12]:
# Creating new column for Total pieces count
sales_data['total_pieces'] = sales_data[['leg_pieces_sold','wings_pieces_sold','lollipop_pieces_sold',
                                         'leg_pieces_leftover','wings_pieces_leftover','lollipop_pieces_leftover']].sum(axis = 1)

# Createing new column for total sold pieces count
sales_data['total_sold_pieces'] = sales_data['total_pieces'] - (sales_data[['leg_pieces_leftover',
                                                                            'wings_pieces_leftover',
                                                                            'lollipop_pieces_leftover']].sum(axis=1))

# Creating new column for total number of pieces leftover

sales_data['total_sold_pieces'] = sales_data['total_pieces'] - (sales_data[['leg_pieces_sold',
                                                                            'wings_pieces_sold',
                                                                            'lollipop_pieces_sold']].sum(axis=1))

# Createing new column for total kg of stock leftover
sales_data['total_leftover_kg'] = sales_data[['leg_leftover_kg','wings_leftover_kg','lollipop_leftover_kg']].sum(axis=1)

# Creating new column for total kg of stock sold

sales_data['total_sold_kg'] = sales_data['total_stock_kg'] - sales_data['total_leftover_kg']

In [13]:
sales_data = sales_data.rename(columns={'toatl_pieces':'total_pieces'})

In [14]:
overbound_filter = sales_data.loc[sales_data['total_stock_kg']  != sales_data[['leg_stock_kg','wings_stock_kg','lollipop_stock_kg']].sum(axis=1)]
overbound_filter

,date,month,total_stock_kg,leg_stock_kg,wings_stock_kg,lollipop_stock_kg,planned_customers,actual_customers_served,total_sales_amount,coupon_uses_count,...,leg_pieces_leftover,wings_pieces_leftover,lollipop_pieces_leftover,leg_leftover_kg,wings_leftover_kg,lollipop_leftover_kg,total_pieces,total_sold_pieces,total_leftover_kg,total_sold_kg
28,2026-03-01,March,13.9,5.56,3.71,4.63,55,55,8489.0,7,...,5,2,0,0.5,0.08,0.00,239,7,0.58,13.32
30,2026-03-03,March,14.7,5.88,3.92,4.90,49,49,7150.0,9,...,20,3,26,2.0,0.12,1.30,254,49,3.42,11.28
31,2026-03-04,March,13.7,5.48,3.65,4.57,52,52,7059.0,6,...,8,41,3,0.8,1.64,0.15,236,52,2.59,11.11
32,2026-03-05,March,10.7,4.28,2.85,3.57,40,40,6396.0,12,...,2,1,3,0.2,0.04,0.15,184,6,0.39,10.31
33,2026-03-06,March,12.7,5.08,3.39,4.23,45,45,6279.0,7,...,18,24,0,1.8,0.96,0.00,218,42,2.76,9.94
37,2026-03-10,March,11.2,4.48,2.99,3.73,31,31,4511.0,3,...,22,29,14,2.2,1.16,0.70,192,65,4.06,7.14
38,2026-03-11,March,11.4,4.56,3.04,3.80,39,39,6305.0,5,...,1,11,20,0.1,0.44,1.00,197,32,1.54,9.86
39,2026-03-12,March,12.9,5.16,3.44,4.30,34,34,5291.0,2,...,21,31,26,2.1,1.24,1.30,223,78,4.64,8.26
41,2026-03-14,March,11.8,4.72,3.15,3.93,31,31,4628.0,4,...,25,13,30,2.5,0.52,1.50,203,68,4.52,7.28
42,2026-03-15,March,14.1,5.64,3.76,4.70,39,39,6344.0,2,...,22,39,10,2.2,1.56,0.50,244,71,4.26,9.84
53,2026-03-26,March,13.6,5.44,3.63,4.53,47,47,6669.0,6,...,0,20,46,0.0,0.80,2.30,234,66,3.10,10.50
55,2026-03-28,March,12.6,5.04,3.36,4.20,34,34,4836.0,8,...,28,19,28,2.8,0.76,1.40,218,75,4.96,7.64
56,2026-03-29,March,12.1,4.84,3.23,4.03,46,46,6279.0,6,...,12,0,20,1.2,0.00,1.00,208,32,2.20,9.90
57,2026-03-30,March,11.8,4.72,3.15,3.93,36,36,5642.0,5,...,19,3,18,1.9,0.12,0.90,203,40,2.92,8.88
58,2026-03-31,March,13.4,5.36,3.57,4.47,52,52,7800.0,9,...,9,4,1,0.9,0.16,0.05,231,14,1.11,12.29
60,2026-04-02,April,12.1,4.84,3.23,4.03,46,46,6851.0,3,...,8,0,12,0.8,0.00,0.60,208,20,1.40,10.70
62,2026-04-04,April,14.1,5.64,3.76,4.70,55,55,7566.0,8,...,8,4,26,0.8,0.16,1.30,244,38,2.26,11.84
63,2026-04-05,April,14.9,5.96,3.97,4.97,50,50,6942.0,6,...,23,29,11,2.3,1.16,0.55,257,63,4.01,10.89
64,2026-04-06,April,11.1,4.44,2.96,3.70,44,44,6825.0,5,...,0,4,6,0.0,0.16,0.30,192,10,0.46,10.64
65,2026-04-07,April,12.7,5.08,3.39,4.23,44,44,6292.0,5,...,8,4,36,0.8,0.16,1.80,218,48,2.76,9.94
67,2026-04-09,April,12.7,5.08,3.39,4.23,49,49,7475.0,4,...,0,4,16,0.0,0.16,0.80,218,20,0.96,11.74
71,2026-04-13,April,12.1,4.84,3.23,4.03,40,40,6097.0,9,...,22,0,4,2.2,0.00,0.20,208,26,2.40,9.70
73,2026-04-15,April,13.6,5.44,3.63,4.53,48,48,6682.0,6,...,26,10,2,2.6,0.40,0.10,234,38,3.10,10.50
74,2026-04-16,April,10.7,4.28,2.85,3.57,41,41,5447.0,9,...,18,1,3,1.8,0.04,0.15,184,22,1.99,8.71
77,2026-04-19,April,11.4,4.56,3.04,3.80,36,36,4940.0,0,...,19,26,16,1.9,1.04,0.80,197,61,3.74,7.66
78,2026-04-20,April,12.9,5.16,3.44,4.30,51,51,7540.0,9,...,9,1,2,0.9,0.04,0.10,223,12,1.04,11.86
79,2026-04-21,April,14.7,5.88,3.92,4.90,59,59,8489.0,5,...,12,3,2,1.2,0.12,0.10,254,17,1.42,13.28
82,2026-04-24,April,14.6,5.84,3.89,4.87,48,48,7189.0,7,...,10,2,45,1.0,0.08,2.25,252,57,3.33,11.27
86,2026-04-28,April,11.2,4.48,2.99,3.73,40,40,5525.0,5,...,14,14,10,1.4,0.56,0.50,192,38,2.46,8.74
88,2026-04-30,April,12.7,5.08,3.39,4.23,38,38,6045.0,5,...,24,4,12,2.4,0.16,0.60,218,40,3.16,9.54
89,2026-05-01,May,11.1,4.44,2.96,3.70,39,39,6058.0,4,...,14,4,2,1.4,0.16,0.10,192,20,1.66,9.44
93,2026-05-05,May,12.7,5.08,3.39,4.23,44,44,6617.0,8,...,20,4,0,2.0,0.16,0.00,218,24,2.16,10.54
94,2026-05-06,May,13.7,5.48,3.65,4.57,38,38,5811.0,3,...,34,16,11,3.4,0.64,0.55,236,61,4.59,9.11
98,2026-05-10,May,14.4,5.76,3.84,4.80,55,55,7644.0,11,...,21,1,4,2.1,0.04,0.20,249,26,2.34,12.06
100,2026-05-12,May,12.9,5.16,3.44,4.30,47,47,6409.0,6,...,9,16,26,0.9,0.64,1.30,223,51,2.84,10.06
102,2026-05-14,May,14.1,5.64,3.76,4.70,42,42,6019.0,7,...,38,4,14,3.8,0.16,0.70,244,56,4.66,9.44
103,2026-05-15,May,12.7,5.08,3.39,4.23,40,40,6058.0,3,...,8,4,44,0.8,0.16,2.20,218,56,3.16,9.54
106,2026-05-18,May,11.3,4.52,3.01,3.77,41,41,5629.0,7,...,17,0,15,1.7,0.00,0.75,195,32,2.45,8.85
111,2026-05-23,May,12.1,4.84,3.23,4.03,41,41,5668.0,4,...,10,15,32,1.0,0.60,1.60,208,57,3.20,8.90
114,2026-05-26,May,12.1,4.84,3.23,4.03,34,34,4914.0,2,...,34,15,8,3.4,0.60,0.40,208,57,4.40,7.70
115,2026-05-27,May,11.3,4.52,3.01,3.77,32,32,4758.0,3,...,25,5,23,2.5,0.20,1.15,195,53,3.85,7.45
116,2026-05-28,May,13.9,5.56,3.71,4.63,44,44,6305.0,5,...,11,17,44,1.1,0.68,2.20,239,72,3.98,9.92
117,2026-05-29,May,12.6,5.04,3.36,4.20,48,48,8021.0,3,...,0,4,0,0.0,0.16,0.00,218,4,0.16,12.44
119,2026-05-31,May,14.9,5.96,3.97,4.97,50,50,7540.0,9,...,25,9,3,2.5,0.36,0.15,257,37,3.01,11.89

In [19]:
sales_data.drop(['month_name','planned_customers'],axis=1,inplace= True)

In [20]:
sales_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      120 non-null    datetime64[us]
 1   month                     120 non-null    str
 2   total_stock_kg            120 non-null    float64
 3   leg_stock_kg              120 non-null    float64
 4   wings_stock_kg            120 non-null    float64
 5   lollipop_stock_kg         120 non-null    float64
 6   actual_customers_served   120 non-null    int64
 7   total_sales_amount        120 non-null    float64
 8   coupon_uses_count         120 non-null    int64
 9   leg_pieces_sold           120 non-null    int64
 10  wings_pieces_sold         120 non-null    int64
 11  lollipop_pieces_sold      120 non-null    int64
 12  leg_pieces_leftover       120 non-null    int64
 13  wings_pieces_leftover     120 non-null    int64
 14  lollipop_pieces_leftover  120 non-null    int64
 15  leg_leftover_kg           120 non-null    float64
 16  wings_leftover_kg         120 non-null    float64
 17  lollipop_leftover_kg      120 non-null    float64
 18  total_pieces              120 non-null    int64
 19  total_sold_pieces         120 non-null    int64
 20  total_leftover_kg         120 non-null    float64
 21  total_sold_kg             120 non-null    float64
dtypes: datetime64[us](1), float64(10), int64(10), str(1)
memory usage: 20.8 KB

In [24]:
# Loading Dataset into DB 
from sqlalchemy import create_engine,text

# Connceting to MYSQL database
username = 'root'
password = 'admin%40123'
port = '3306'
host = 'localhost'
database = 'bbq_brothers'

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

In [26]:
sales_data.to_sql("stocks",engine,if_exists='replace',index=False)

120

In [28]:
sql_check = pd.read_sql("select * from stocks limit 5;",con=engine)
print(sql_check)

        date     month  total_stock_kg  leg_stock_kg  wings_stock_kg  \
0 2026-02-01  February            15.0           6.0             4.0
1 2026-02-02  February            15.0           6.0             4.0
2 2026-02-03  February            15.0           6.0             4.0
3 2026-02-04  February            15.0           6.0             4.0
4 2026-02-05  February            15.0           6.0             4.0

   lollipop_stock_kg  actual_customers_served  total_sales_amount  \
0                5.0                       53              7605.0
1                5.0                       58              8671.0
2                5.0                       60              8970.0
3                5.0                       60              8905.0
4                5.0                       54              7527.0

   coupon_uses_count  leg_pieces_sold  ...  leg_pieces_leftover  \
0                  4               42  ...                   18
1                  3               56  ...                    4
2                  9               60  ...                    0
3                  5               48  ...                   12
4                 10               44  ...                   16

   wings_pieces_leftover  lollipop_pieces_leftover  leg_leftover_kg  \
0                      0                        28              1.8
1                      0                        24              0.4
2                      5                        16              0.0
3                      0                         0              1.2
4                      0                        32              1.6

   wings_leftover_kg  lollipop_leftover_kg  total_pieces  total_sold_pieces  \
0                0.0                   1.4           260                 46
1                0.0                   1.2           260                 28
2                0.2                   0.8           260                 21
3                0.0                   0.0           260                 12
4                0.0                   1.6           260                 48

   total_leftover_kg  total_sold_kg
0                3.2           11.8
1                1.6           13.4
2                1.0           14.0
3                1.2           13.8
4                3.2           11.8

[5 rows x 22 columns]

In [31]:
#Exporting as csv file
sales_data.to_csv(r"C:\Users\wwwsi\OneDrive\Documents\Project Brothers BBQ\Dataset _\Cleaned_data\cleaned_stocks.csv", index=False)