In [1]:
import pandas as pd
import numpy as np

In [2]:
#sales_data = pd.read_csv(r"C:\Users\wwwsi\OneDrive\Documents\Project Brothers BBQ\Dataset _\Total_Monthly_Sales.csv")
Transction_data = pd.read_csv(r"C:\Users\wwwsi\OneDrive\Documents\Project Brothers BBQ\Dataset _\raw\sales_transactions.csv")

In [3]:
Transction_data.head()

,date,time_of_purchase,customer_name,phone_number,age,order_type,item_bought,is_combo,quantity,item_price_total,coupon_code,coupon_used,discount_amount,final_amount,payment_method,rating,review
0,2026-02-01,19:52,Kavya Raj,+91 7799371240,NaN,Walk-in,Chicken Leg (2 pc),No,1,130,karur_kalam,No,0,130,GPay,5.0,NaN
1,2026-02-01,20:31,Nithya Babu,+91 9120826773,33.0,Phone Call,Chicken Wings (5 pc),No,1,130,karur_kalam,No,0,130,GPay,NaN,"Wings semma crispy ah irundhuchu, thanks anna"
2,2026-02-01,18:49,Kumar S,+91 8467854458,46.0,Walk-in,Chicken Wings (5 pc),No,1,130,karur_kalam,No,0,130,Card,3.0,NaN
3,2026-02-01,21:26,Ravi K,+91 7054932966,47.0,Phone Call,Chicken Wings (5 pc),No,2,260,karur_kalam,No,0,260,PhonePe,5.0,"Chicken leg romba soft ah vekachu irundhuchu, ..."
4,2026-02-01,20:37,Meena Prasad,+91 6902294131,50.0,Walk-in,Chicken Leg (2 pc),No,1,130,karur_kalam,No,0,130,GPay,5.0,Very tasty and quick service too

In [4]:
Transction_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5238 entries, 0 to 5237
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              5238 non-null   str
 1   time_of_purchase  5238 non-null   str
 2   customer_name     4916 non-null   str
 3   phone_number      5238 non-null   str
 4   age               4452 non-null   float64
 5   order_type        5238 non-null   str
 6   item_bought       5238 non-null   str
 7   is_combo          5238 non-null   str
 8   quantity          5238 non-null   int64
 9   item_price_total  5238 non-null   int64
 10  coupon_code       5238 non-null   str
 11  coupon_used       5238 non-null   str
 12  discount_amount   5238 non-null   int64
 13  final_amount      5238 non-null   int64
 14  payment_method    5088 non-null   str
 15  rating            4177 non-null   float64
 16  review            3496 non-null   str
dtypes: float64(2), int64(4), str(11)
memory usage: 695.8 KB

In [5]:
Transction_data['date'] = pd.to_datetime(Transction_data["date"],errors = 'coerce')
Transction_data['time_of_purchase'] = pd.to_datetime(Transction_data['time_of_purchase'],errors = 'coerce')
Transction_data['age'] = Transction_data['age'].astype("Int64")
Transction_data['Item_price_total'] = Transction_data['item_price_total'].astype("float64")
Transction_data['discount_amount'] = Transction_data['discount_amount'].astype("float64")
Transction_data['final_amount'] = Transction_data['final_amount'].astype("float64")

C:\Users\wwwsi\AppData\Local\Temp\ipykernel_21528\1337635768.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Transction_data['time_of_purchase'] = pd.to_datetime(Transction_data['time_of_purchase'],errors = 'coerce')

In [6]:
Transction_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5238 entries, 0 to 5237
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              5238 non-null   datetime64[us]
 1   time_of_purchase  5238 non-null   datetime64[us]
 2   customer_name     4916 non-null   str
 3   phone_number      5238 non-null   str
 4   age               4452 non-null   Int64
 5   order_type        5238 non-null   str
 6   item_bought       5238 non-null   str
 7   is_combo          5238 non-null   str
 8   quantity          5238 non-null   int64
 9   item_price_total  5238 non-null   int64
 10  coupon_code       5238 non-null   str
 11  coupon_used       5238 non-null   str
 12  discount_amount   5238 non-null   float64
 13  final_amount      5238 non-null   float64
 14  payment_method    5088 non-null   str
 15  rating            4177 non-null   float64
 16  review            3496 non-null   str
 17  Item_price_total  5238 non-null   float64
dtypes: Int64(1), datetime64[us](2), float64(4), int64(2), str(9)
memory usage: 741.8 KB

In [7]:
missing_values = ["N/A", "NA", "na", "NaN", "NULL", "null", "Missing", ""]
Transction_data.isin(missing_values).sum()

date                0
time_of_purchase    0
customer_name       0
phone_number        0
age                 0
order_type          0
item_bought         0
is_combo            0
quantity            0
item_price_total    0
coupon_code         0
coupon_used         0
discount_amount     0
final_amount        0
payment_method      0
rating              0
review              0
Item_price_total    0
dtype: Int64

In [8]:
# Search for missing values
print(Transction_data.shape)
Transction_data.isnull().sum()

(5238, 18)

date                   0
time_of_purchase       0
customer_name        322
phone_number           0
age                  786
order_type             0
item_bought            0
is_combo               0
quantity               0
item_price_total       0
coupon_code            0
coupon_used            0
discount_amount        0
final_amount           0
payment_method       150
rating              1061
review              1742
Item_price_total       0
dtype: int64

In [9]:
# Filling Missing Values
# Assuming IF Card or UPI like digital payment have the Transcation history and Details
# Hard-Cash will be the one most likely have the possibility forget to entry
Transction_data["payment_method"] = Transction_data["payment_method"].fillna('Cash')

In [10]:
Transction_data['rating'] = Transction_data['rating'].fillna('Not rated')
#Transction_data['age'] = Transction_data['age'].fillna('Unknown')

In [11]:
Transction_data['customer_name'] = (Transction_data.groupby('phone_number')['customer_name'].transform(lambda x:x.ffill().bfill()))
Transction_data['customer_name'] = Transction_data['customer_name'].fillna("Unknown")

In [12]:
Transction_data['age_num'] = Transction_data['age'].replace('Unknown',np.nan).astype("Int64")

In [13]:
cols = list(Transction_data.columns)
cols.remove("age_num")
cols.insert(cols.index("age")+1,"age_num")
cols

['date',
 'time_of_purchase',
 'customer_name',
 'phone_number',
 'age',
 'age_num',
 'order_type',
 'item_bought',
 'is_combo',
 'quantity',
 'item_price_total',
 'coupon_code',
 'coupon_used',
 'discount_amount',
 'final_amount',
 'payment_method',
 'rating',
 'review',
 'Item_price_total']

In [14]:
Transction_data = Transction_data[cols]
Transction_data.head(10)

,date,time_of_purchase,customer_name,phone_number,age,age_num,order_type,item_bought,is_combo,quantity,item_price_total,coupon_code,coupon_used,discount_amount,final_amount,payment_method,rating,review,Item_price_total
0,2026-02-01,2026-08-01 19:52:00,Kavya Raj,+91 7799371240,<NA>,<NA>,Walk-in,Chicken Leg (2 pc),No,1,130,karur_kalam,No,0.0,130.0,GPay,5.0,NaN,130.0
1,2026-02-01,2026-08-01 20:31:00,Nithya Babu,+91 9120826773,33,33,Phone Call,Chicken Wings (5 pc),No,1,130,karur_kalam,No,0.0,130.0,GPay,Not rated,"Wings semma crispy ah irundhuchu, thanks anna",130.0
2,2026-02-01,2026-08-01 18:49:00,Kumar S,+91 8467854458,46,46,Walk-in,Chicken Wings (5 pc),No,1,130,karur_kalam,No,0.0,130.0,Card,3.0,NaN,130.0
3,2026-02-01,2026-08-01 21:26:00,Ravi K,+91 7054932966,47,47,Phone Call,Chicken Wings (5 pc),No,2,260,karur_kalam,No,0.0,260.0,PhonePe,5.0,"Chicken leg romba soft ah vekachu irundhuchu, ...",260.0
4,2026-02-01,2026-08-01 20:37:00,Meena Prasad,+91 6902294131,50,50,Walk-in,Chicken Leg (2 pc),No,1,130,karur_kalam,No,0.0,130.0,GPay,5.0,Very tasty and quick service too,130.0
5,2026-02-01,2026-08-01 20:36:00,Kavya K,+91 6135290965,42,42,Walk-in,Chicken Leg (2 pc),No,1,130,karur_kalam,Yes,13.0,117.0,GPay,3.0,"Average, expected more spice",130.0
6,2026-02-01,2026-08-01 19:58:00,Sathish Kumar,+91 8843443757,37,37,Phone Call,Chicken Lollipop (4 pc),No,1,130,karur_kalam,No,0.0,130.0,GPay,4.0,"Great value for money, fresh and hot",130.0
7,2026-02-01,2026-08-01 20:43:00,Anitha Raj,+91 8738757177,35,35,Walk-in,Chicken Wings (5 pc),No,1,130,karur_kalam,Yes,13.0,117.0,PhonePe,2.0,NaN,130.0
8,2026-02-01,2026-08-01 18:42:00,Muthu Babu,+91 6455623869,58,58,Phone Call,Chicken Wings (5 pc),No,1,130,karur_kalam,No,0.0,130.0,PhonePe,Not rated,"Best chicken lollipop I've had, will come again",130.0
9,2026-02-01,2026-08-01 21:51:00,Suresh K,+91 6531003309,24,24,Phone Call,Chicken Leg (2 pc),No,1,130,karur_kalam,No,0.0,130.0,GPay,4.0,NaN,130.0

In [15]:
#removing redunency columns
Transction_data.drop(['coupon_code','review'],axis = 1,inplace = True)

In [16]:
Transction_data.head()

,date,time_of_purchase,customer_name,phone_number,age,age_num,order_type,item_bought,is_combo,quantity,item_price_total,coupon_used,discount_amount,final_amount,payment_method,rating,Item_price_total
0,2026-02-01,2026-08-01 19:52:00,Kavya Raj,+91 7799371240,<NA>,<NA>,Walk-in,Chicken Leg (2 pc),No,1,130,No,0.0,130.0,GPay,5.0,130.0
1,2026-02-01,2026-08-01 20:31:00,Nithya Babu,+91 9120826773,33,33,Phone Call,Chicken Wings (5 pc),No,1,130,No,0.0,130.0,GPay,Not rated,130.0
2,2026-02-01,2026-08-01 18:49:00,Kumar S,+91 8467854458,46,46,Walk-in,Chicken Wings (5 pc),No,1,130,No,0.0,130.0,Card,3.0,130.0
3,2026-02-01,2026-08-01 21:26:00,Ravi K,+91 7054932966,47,47,Phone Call,Chicken Wings (5 pc),No,2,260,No,0.0,260.0,PhonePe,5.0,260.0
4,2026-02-01,2026-08-01 20:37:00,Meena Prasad,+91 6902294131,50,50,Walk-in,Chicken Leg (2 pc),No,1,130,No,0.0,130.0,GPay,5.0,130.0

In [17]:
Transction_data[Transction_data.duplicated(keep = 'first')]

Empty DataFrame
Columns: [date, time_of_purchase, customer_name, phone_number, age, age_num, order_type, item_bought, is_combo, quantity, item_price_total, coupon_used, discount_amount, final_amount, payment_method, rating, Item_price_total]
Index: []

In [18]:
# Reload the original raw CSV just to get a clean time_of_purchase column
raw = pd.read_csv(r"C:\Users\wwwsi\OneDrive\Documents\Project Brothers BBQ\Dataset _\raw\sales_transactions.csv")

# Parse time-only, no format guessing, no date attached
Transction_data['time_of_purchase'] = pd.to_datetime(
    raw['time_of_purchase'], format='%H:%M', errors='coerce'
).dt.time

# Now combine with date into one real timestamp
Transction_data['purchase_datetime'] = pd.to_datetime(
    Transction_data['date'].astype(str) + ' ' + Transction_data['time_of_purchase'].astype(str),
    errors='coerce'
)

print(Transction_data[['date', 'time_of_purchase', 'purchase_datetime']].head())
print(Transction_data['purchase_datetime'].isnull().sum(), "rows failed to parse")

        date time_of_purchase   purchase_datetime
0 2026-02-01         19:52:00 2026-02-01 19:52:00
1 2026-02-01         20:31:00 2026-02-01 20:31:00
2 2026-02-01         18:49:00 2026-02-01 18:49:00
3 2026-02-01         21:26:00 2026-02-01 21:26:00
4 2026-02-01         20:37:00 2026-02-01 20:37:00
0 rows failed to parse

In [19]:
Transction_data.head()

,date,time_of_purchase,customer_name,phone_number,age,age_num,order_type,item_bought,is_combo,quantity,item_price_total,coupon_used,discount_amount,final_amount,payment_method,rating,Item_price_total,purchase_datetime
0,2026-02-01,19:52:00,Kavya Raj,+91 7799371240,<NA>,<NA>,Walk-in,Chicken Leg (2 pc),No,1,130,No,0.0,130.0,GPay,5.0,130.0,2026-02-01 19:52:00
1,2026-02-01,20:31:00,Nithya Babu,+91 9120826773,33,33,Phone Call,Chicken Wings (5 pc),No,1,130,No,0.0,130.0,GPay,Not rated,130.0,2026-02-01 20:31:00
2,2026-02-01,18:49:00,Kumar S,+91 8467854458,46,46,Walk-in,Chicken Wings (5 pc),No,1,130,No,0.0,130.0,Card,3.0,130.0,2026-02-01 18:49:00
3,2026-02-01,21:26:00,Ravi K,+91 7054932966,47,47,Phone Call,Chicken Wings (5 pc),No,2,260,No,0.0,260.0,PhonePe,5.0,260.0,2026-02-01 21:26:00
4,2026-02-01,20:37:00,Meena Prasad,+91 6902294131,50,50,Walk-in,Chicken Leg (2 pc),No,1,130,No,0.0,130.0,GPay,5.0,130.0,2026-02-01 20:37:00

In [20]:
# Checking Quality of columns
for x in ["final_amount","discount_amount","item_price_total"]:
    has_negative= (Transction_data[x]<0).any()
    print(f"{x}: {has_negative} ")

final_amount: False
discount_amount: False
item_price_total: False

In [21]:
valid_rating = Transction_data.loc[Transction_data["rating"] != "Not rated"]
is_valid = ((valid_rating["rating"] >= 1) & (valid_rating["rating"] <= 5)).any()
print(is_valid)

True

In [22]:
# Categorical Quality of columns
categorical_columns = ['order_type','is_combo','coupon_used','payment_method']
for x in categorical_columns:
    print(f"\n{Transction_data[x].value_counts()}")

order_type
Walk-in       3118
Phone Call    2120
Name: count, dtype: int64

is_combo
No    5238
Name: count, dtype: int64

coupon_used
No     4451
Yes     787
Name: count, dtype: int64

payment_method
Cash       1801
GPay       1710
PhonePe    1112
Paytm       449
Card        166
Name: count, dtype: int64

In [23]:
pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in C:\Users\wwwsi\anaconda3\envs\bbq_brothers_env\Lib\site-packages (2.9.12)
Note: you may need to restart the kernel to use updated packages.

In [24]:
pip install pymysql

Requirement already satisfied: pymysql in C:\Users\wwwsi\anaconda3\envs\bbq_brothers_env\Lib\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

In [25]:
from sqlalchemy import create_engine, text

# MySQL connection details
username = "root"
password = "admin%40123"   # URL-encoded @ -> %40
host = "localhost"
port = "3306"
database = "bbq_brothers"

# Step 1: connect without specifying a database, to create it if needed
engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/')

with engine.begin() as conn:   # engine.begin() auto-commits
    conn.execute(text("CREATE DATABASE IF NOT EXISTS bbq_brothers"))

# Step 2: reconnect, now pointing at the actual database
engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

In [26]:
Transction_data.drop('Item_price_total',axis = 1 ,inplace = True)

In [27]:
# Step 3: push the cleaned dataframe into a table
Transction_data.to_sql("customer_transction", con=engine, if_exists="replace", index=False)

5238

In [28]:
import pandas as pd

df_check = pd.read_sql("SELECT * FROM customer_transction LIMIT 5;", con=engine)
print(df_check)

        date time_of_purchase customer_name    phone_number   age  age_num  \
0 2026-02-01  0 days 19:52:00     Kavya Raj  +91 7799371240   NaN      NaN
1 2026-02-01  0 days 20:31:00   Nithya Babu  +91 9120826773  33.0     33.0
2 2026-02-01  0 days 18:49:00       Kumar S  +91 8467854458  46.0     46.0
3 2026-02-01  0 days 21:26:00        Ravi K  +91 7054932966  47.0     47.0
4 2026-02-01  0 days 20:37:00  Meena Prasad  +91 6902294131  50.0     50.0

   order_type           item_bought is_combo  quantity  item_price_total  \
0     Walk-in    Chicken Leg (2 pc)       No         1               130
1  Phone Call  Chicken Wings (5 pc)       No         1               130
2     Walk-in  Chicken Wings (5 pc)       No         1               130
3  Phone Call  Chicken Wings (5 pc)       No         2               260
4     Walk-in    Chicken Leg (2 pc)       No         1               130

  coupon_used  discount_amount  final_amount payment_method     rating  \
0          No              0.0         130.0           GPay          5
1          No              0.0         130.0           GPay  Not rated
2          No              0.0         130.0           Card          3
3          No              0.0         260.0        PhonePe          5
4          No              0.0         130.0           GPay          5

    purchase_datetime
0 2026-02-01 19:52:00
1 2026-02-01 20:31:00
2 2026-02-01 18:49:00
3 2026-02-01 21:26:00
4 2026-02-01 20:37:00

In [31]:
Transction_data["time_of_purchase"] = pd.to_datetime(
    Transction_data["time_of_purchase"], format="%H:%M:%S"
)

In [34]:
Transction_data["rating"] = Transction_data["rating"].astype("str")

In [35]:
Transction_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5238 entries, 0 to 5237
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               5238 non-null   datetime64[us]
 1   time_of_purchase   5238 non-null   datetime64[us]
 2   customer_name      5238 non-null   str
 3   phone_number       5238 non-null   str
 4   age                4452 non-null   Int64
 5   age_num            4452 non-null   Int64
 6   order_type         5238 non-null   str
 7   item_bought        5238 non-null   str
 8   is_combo           5238 non-null   str
 9   quantity           5238 non-null   int64
 10  item_price_total   5238 non-null   int64
 11  coupon_used        5238 non-null   str
 12  discount_amount    5238 non-null   float64
 13  final_amount       5238 non-null   float64
 14  payment_method     5238 non-null   str
 15  rating             5238 non-null   str
 16  purchase_datetime  5238 non-null   datetime64[us]
dtypes: Int64(2), datetime64[us](3), float64(2), int64(2), str(8)
memory usage: 706.0 KB

In [36]:
Transction_data.to_parquet(r"C:\Users\wwwsi\OneDrive\Documents\Project Brothers BBQ\Dataset _\Cleaned_data\TransactionData_cleaned.parquet",index=False)

In [ ]:
#conda install -c conda-forge pyarrow

In [ ]:
#conda install -c conda-forge fastparquet